### ISSUE TITLE
How to profile DDR bandwidth?

### ISSUE THREAD

**Issue by logosAllen** [arc-research-lab/CHARM#15]
Hi,
I have seen there is a Bandwidth Profiler before DSE in fig6 of CHARM paper.
And I want to reproduce it on my vck5000 since the it has 4 DRAM bank.
But in cdse.py, the bandwidth part is fixed, how did you profile the bandwidth of the FPGA?
  ```python
  # One-Time Profling of DDR Bandwidth
      BW_L_S=(12*DDR_BANK)*freq_rate
      BW_R_S=(12*DDR_BANK)*freq_rate
      BW_O_S=(8.5*DDR_BANK)*freq_rate
  
      BW_L_DR=(8*DDR_BANK)*freq_rate
      BW_R_DL=(8*DDR_BANK)*freq_rate
  
      BW_L_DO=(8*DDR_BANK)*freq_rate
      BW_R_DO=(8*DDR_BANK)*freq_rate
      BW_O_D=(6*DDR_BANK)*freq_rate
  
      BW_L_T=(7*DDR_BANK)*freq_rate
      BW_R_T=(7*DDR_BANK)*freq_rate
      BW_O_T=(7*DDR_BANK)*freq_rate
  ``` 
Thank you.

**Comment by JinmingZhuang** [comment]
Hi,

For VCK190 which has one DDR4 bank, I could point you to this repo for the DDR bandwidth profiling.

https://github.com/SFU-HiAccel/uBench

For VCK5000 which has 4 DDR4 banks, to the best of our knowledge, we can't assign the AXI Port to a specific bank through the Vitis Flow with the pre-built platform.

Best,
Jinming
