### ISSUE TITLE
ERROR: [v++ 60-602] Source file does not exist: hw.xclbin

### ISSUE THREAD

**Issue by yiou-seal** [arc-research-lab/CHARM#16]
Hi,

I am facing a problem when running command 
`python project_setup.py`
I got the error: 
`ERROR: [v++ 60-602] Source file does not exist: /home/[myusername]/xxxx/CHARM/prj_try/build_dir.hw.xilinx_vck190_base_202220_1/hw.xclbin`
I'm wondering if this has something to do with the vitis 2022.2 version I'm using, or a misconfiguration somewhere

The complete log is as follows：

`mkdir -p ./build_dir.hw.xilinx_vck190_base_202220_1
v++ -l -t hw --platform /s3/Xilinx_Vitis_2022.2/Vitis/2022.2/base_platforms/xilinx_vck190_base_202220_1/xilinx_vck190_base_202220_1.xpfm --save-temps --optimize 2 --hls.jobs 8 --config ./conn.cfg --clock.defaultFreqHz 220000000 --temp_dir ./build_dir.hw.xilinx_vck190_base_202220_1 --vivado.synth.jobs 8 --vivado.impl.jobs 8 -o'build_dir.hw.xilinx_vck190_base_202220_1/hw.xclbin' _x.hw.xilinx_vck190_base_202220_1/dma.xo libadf.a | tee ./build_dir.hw.xilinx_vck190_base_202220_1/hpc_xclbin.log
Option Map File Used: '/s3/Xilinx_Vitis_2022.2/Vitis/2022.2/data/vitis/vpp/optMap.xml'

****** v++ v2022.2 (64-bit)
  **** SW Build 3671529 on 2022-10-13-17:52:11
    ** Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.

objcopy: warning: /home/[myusername]/xxxx/CHARM/prj_try/.Xil/v++-37415-[myusername]/hw.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010002
objcopy: warning: /home/[myusername]/xxxx/CHARM/prj_try/.Xil/v++-37415-[myusername]/hw.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010001
objcopy: warning: /home/[myusername]/xxxx/CHARM/prj_try/.Xil/v++-37415-[myusername]/sw.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010002
objcopy: warning: /home/[myusername]/xxxx/CHARM/prj_try/.Xil/v++-37415-[myusername]/sw.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010001
INFO: [v++ 60-1306] Additional information associated with this v++ link can be found at:
	Reports: /home/[myusername]/xxxx/CHARM/prj_try/build_dir.hw.xilinx_vck190_base_202220_1/reports/link
	Log files: /home/[myusername]/xxxx/CHARM/prj_try/build_dir.hw.xilinx_vck190_base_202220_1/logs/link
Running Dispatch Server on port: 37909
INFO: [v++ 60-1548] Creating build summary session with primary output /home/[myusername]/xxxx/CHARM/prj_try/build_dir.hw.xilinx_vck190_base_202220_1/hw.xclbin.link_summary, at Fri Jul 21 16:59:57 2023
INFO: [v++ 60-1315] Creating rulecheck session with output '/home/[myusername]/xxxx/CHARM/prj_try/build_dir.hw.xilinx_vck190_base_202220_1/reports/link/v++_link_hw_guidance.html', at Fri Jul 21 16:59:57 2023
INFO: [v++ 60-895]   Target platform: /s3/Xilinx_Vitis_2022.2/Vitis/2022.2/base_platforms/xilinx_vck190_base_202220_1/xilinx_vck190_base_202220_1.xpfm
INFO: [v++ 60-1578]   This platform contains Xilinx Shell Archive '/s3/Xilinx_Vitis_2022.2/Vitis/2022.2/base_platforms/xilinx_vck190_base_202220_1/hw/hw.xsa'
ERROR: [v++ 82-4223] Output file type of .xsa is required. A different output file type has been specified: build_dir.hw.xilinx_vck190_base_202220_1/hw.xclbin
INFO: [v++ 60-1653] Closing dispatch client.
v++ -p -t hw -f /s3/Xilinx_Vitis_2022.2/Vitis/2022.2/base_platforms/xilinx_vck190_base_202220_1/xilinx_vck190_base_202220_1.xpfm \
	--package.out_dir ./package.hw \
	--package.rootfs /opt/xilinx-versal-common-v2022.2/rootfs.ext4 \
	--package.kernel_image /opt/xilinx-versal-common-v2022.2/Image \
	--package.boot_mode=sd \
	--package.image_format=ext4 \
	--package.defer_aie_run \
	--package.sd_file hostexe \
	libadf.a ./build_dir.hw.xilinx_vck190_base_202220_1/hw.xclbin -o mm_hw.xclbin
Option Map File Used: '/s3/Xilinx_Vitis_2022.2/Vitis/2022.2/data/vitis/vpp/optMap.xml'

****** v++ v2022.2 (64-bit)
  **** SW Build 3671529 on 2022-10-13-17:52:11
    ** Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.

ERROR: [v++ 60-602] Source file does not exist: /home/[myusername]/xxxx/CHARM/prj_try/build_dir.hw.xilinx_vck190_base_202220_1/hw.xclbin
INFO: [v++ 60-1662] Stopping dispatch session having empty uuid.
INFO: [v++ 60-1653] Closing dispatch client.
make: *** [Makefile:185: package_hw] Error 1`

Thanks
Yiou

**Comment by kediarajesh** [comment]
@yiou-seal - is this resolved? I am also facing this issue.

**Comment by JinmingZhuang** [comment]
Hi,

Thank you for your interest in our CHARM project!

It seems that the "xclbin" file is not correctly generated. As the Vitis version being used is 2022.2, I would suggest to check if AIE binary i.e. "libadf.a" has been correctly generated.

Best,
Jinming
