### ISSUE TITLE
how to run sd card image on qemu ? please provide some insights for testing the images built after make all command on qemu emulation

### ISSUE THREAD

**Issue by Prathmesh-shalu141** [arc-research-lab/CHARM#34]

**Comment by JinmingZhuang** [comment]
After running "make all", there should be a folder called "package.hw_emu", emulation should work by following these steps :

```sh
$ cd package.hw_emu
$ ./launch_hw_emu.sh
```

When the emulated petalinux is up, run:
```sh
$ cd /mnt/sd-mmcblk0p1
$ ./hostexe mm_hw_emu.xclbin {M} {K} {N} {iteration} {verify}
```

**Comment by Prathmesh-shalu141** [comment]
I do not have 'launch_hw_emu.sh' file in that package.folder, please provide the necessary details .

![image](https://github.com/arc-research-lab/CHARM/assets/160479228/0fd529df-ce1f-45d1-a6ac-2c3705e71eda)

**Comment by JinmingZhuang** [comment]
Seems that your target is set to "hw" which is for on-board testing. 

1) If you want to do real on-board testing on VCK190, you can flash the "sd_card.img" file into your SD card and boot the device. 
2) If you want to do the hardware simulation, you could run:
```sh
make all TARGET=hw_emu
```
Then follow the steps mentioned above https://github.com/arc-research-lab/CHARM/issues/34#issuecomment-2065661888

**Comment by Prathmesh-shalu141** [comment]
Getting this error after launching launch_hw_emu.sh file  Please provide the  appropriate steps for doing emulation successfully

![image](https://github.com/arc-research-lab/CHARM/assets/160479228/dbfe6d4c-f2c0-45ea-87cd-29181db96ecd)
