### ISSUE TITLE
Both HW and HW_emu failed to complete execution on certain MM scales

### ISSUE THREAD

**Issue by Albresky** [arc-research-lab/CHARM#42]
As described in the title, when using the AutoMM Python interface to generate projects for specific scales, such as $2048 \times 2048 \times 2048$ with the data type int16, we obtained the expected code, which compiled successfully on Vitis 2021.1. However, when we attempted to run this build in emulation or on the VCK190 board, the program became unresponsive and did not exit.

In contrast, other scales, such as $1024 \times 1024 \times 1024$ and $4096 \times 4096\times 4096$, the generated code executed as expected in both hardware emulation and on the board.

Below is the Python code used to generate the projects that get stuck during execution:

```python
import os
import sys
import subprocess
import numpy as np
cur_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.append(cur_dir)
from charm import* 

#Set the design project path
prj_dir= cur_dir + '/prj_try'
subprocess.run(['mkdir','-p' ,f'{prj_dir}'])

#Define the left-hand-side(A) and right-hide-side(B) operands
A=np.random.rand(2048, 2048).astype(np.int16) ################ The data type is int16
B=np.random.rand(2048, 2048).astype(np.int16)

#Create the object of the class charm
automm=charm(prj_dir)

#Launch charm dse to find optimized hardware configuration
Versal_config=automm.cdse(A,B)

#Launch charm automatic code generator to emit the code for AIE, PL and Host CPU
device='vck190' # Supported devices are vck190 and vck5000
automm.cacg(Versal_config,device)

# #Run Vitis Compilation Flow
# automm.build()
```

**Comment by Albresky** [comment]
Here is a case for $256 \times 256 \times 256$ build running on board VCK190.

![image](https://github.com/user-attachments/assets/58421693-304c-43a8-9e54-af78db328e08)

**Comment by JinmingZhuang** [comment]
Hi,

The current CDSE is deterministic meaning the same settings in "_project_setup.py_" resulting in the same hardware configuration. However, the hardware configurations I generated are different than yours. I find this from your printing information where M=288, K=288, N=384. Could you please describe how this hardware design is generated?

**Comment by Albresky** [comment]
> Hi,
> 
> The current CDSE is deterministic meaning the same settings in "_project_setup.py_" resulting in the same hardware configuration. However, the hardware configurations I generated are different than yours. I find this from your printing information where M=288, K=288, N=384. Could you please describe how this hardware design is generated?

Hi~

I generated the project by manually setting params in line 14-15 of `project_setup.py`, and targetting the data type as `np.int16`: 
```cpp
A=np.random.rand(256, 256).astype(np.int16)
B=np.random.rand(256, 256).astype(np.int16)
```
As for the output information *where M=288, K=288, N=384*, this is a printf() added to `host.cpp`, which prints the value of `M`, `K` and `N` in line 129-131 from `templates/host/kernel0/host.cpp`:
```cpp
int M =TX0 * M_ACC0;
int K =TY0 * K_ACC0;
int N =TZ0 * N_ACC0;
```

In the original sourcecode of CHARM, the host.cpp prints only the MM size of user's input, namely `M1`, `K1` and `N1`. As far as I know, CHARM adds paddings to the original MM size from  `M1`, `K1`, `N1` to  `M`, `K`, `N` to conduct MM operations. Both variable `M` and `M1` are defined by CHARM, what I've done is adding a printf() sentence to output these values to stdout.

**Comment by JinmingZhuang** [comment]
Hi,

I have set the matrix size to 256:
```python
A=np.random.rand(256, 256).astype(np.int16)
B=np.random.rand(256, 256).astype(np.int16)
```

The generated parameters in the host are listed below:
![image](https://github.com/user-attachments/assets/2dae4e09-5c1b-4d7d-a3af-d46c00ca7650)

I think all of M, K, and N should equal 288. Is this the same configuration on your end?

**Comment by Albresky** [comment]
> Hi,
> 
> I have set the matrix size to 256:
> 
> ```python
> A=np.random.rand(256, 256).astype(np.int16)
> B=np.random.rand(256, 256).astype(np.int16)
> ```
> 
> The generated parameters in the host are listed below: ![image](https://private-user-images.githubusercontent.com/77606152/383794206-2dae4e09-5c1b-4d7d-a3af-d46c00ca7650.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NjA3NjYsIm5iZiI6MTczMDk2MDQ2NiwicGF0aCI6Ii83NzYwNjE1Mi8zODM3OTQyMDYtMmRhZTRlMDktNWMxYi00ZDdkLWEzYWYtZDQ2YzAwY2E3NjUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDA2MjEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhMzE2NGVhMGYxMjYwNzllNWIxYmI5YjI3ODM1MDM1MmZhZTQ0OTkzNWI3OWRlNWExMDllNzk5OTY0YTBlYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5ipIHXRcZ0K3ozWOcIa84S2SnBNe41ZRuvncWBrgzk4)
> 
> I think all of M, K, and N should equal 288. Is this the same configuration on your end?

Sorry, I've uploaded the wrong screenshot. Below is the correct built for $256 \times 256 \times 256$, and all the $M$, $K$ and $N$ seems correct:

![image](https://github.com/user-attachments/assets/17f81697-aafb-4cc5-b86f-f4ee6e31b3a0)

However, the on board running still got stuck:

![image](https://github.com/user-attachments/assets/f12f7f15-d3ad-405c-924b-1b5f972d9edd)

**Comment by JinmingZhuang** [comment]
Hi,

The reason for the stuck is that the current code generator for INT16 data type in CHARM only supports A%2=0 to pack the AXI port width to 512 bits. I have cut the design space in the CDSE to fix the problem. Please use the latest version.

Best,
