### ISSUE TITLE
Vkc190 Simulator? 

### ISSUE THREAD

**Issue by srikanthmalla** [arc-research-lab/CHARM#5]
Hi @JinmingZhuang 
Great work! I am working in machine learning. But I'm a beginner to FPGA and learning about machine learning implementation on FPGA. Your work seems latest and a good start point. Since FPGA boards are not easily available to everyone, more specifically vkc190. For learning purpose, could you also make a tutorial or show some pointers for beginners like me, how to use run your code or use it in a xilinx simulator in linux/ubuntu? I'm also not sure if there is any simulator like that. Please let me know.

Thank you!
Srikanth

**Comment by JinmingZhuang** [comment]
Hi @srikanthmalla,

Thank you for reaching out. 

- For the whole system(AIE+PL+Host), Vitis supports hardware emulation. Users can change the "TARGET=hw_emu" in the "Makefile"; For AIE, there is a cycle accurate simulator which can be referenced to [AIE Simulator](https://docs.xilinx.com/r/2021.1-English/ug1076-ai-engine-environment/AI-Engine-SystemC-Simulator). To try the AIE simulator, one quickest way is following these steps in our repo (with Vitis2021.1 and AIE License installed):
```
./project_setup.sh ./config_files/input.cfg aie_project
cd aie_project
make aiesim
```

- There are some tutorials and documentations of Versal ACAP for designers to look at:

- Tutorials:

1. [Simple Example for AIE](https://github.com/Xilinx/Vitis_Accel_Examples/tree/master/aie_kernels): A good starting point tutorial to get familiar with the whole compilation flow of Versal ACAP.
2. [Features and Designs of AIE](https://github.com/Xilinx/Vitis-Tutorials/tree/2022.2/AI_Engine_Development): A repo to learn AIE Features, such as "Window" and "Steam" connections.
3. **This repo CHARM: A good reference for Matrix Multiply design including single AIE, AIE array, PL and the whole system**.

- Documentations:

1. [AIE Architecture](https://docs.xilinx.com/r/en-US/am009-versal-ai-engine): A document for understanding AIE Architecture.
3. [AIE Processor Design](https://docs.xilinx.com/r/2021.1-English/ug1079-ai-engine-kernel-coding/Revision-History): A document for single AIE coding.
4. [Versal Programming Environment](https://docs.xilinx.com/r/2021.1-English/ug1076-ai-engine-environment/Revision-History): A document for Versal design including AIE API, Host coding, AIE+ PL+ Host Integration and so on.

Best.
Jinming
