### ISSUE TITLE
non-GEMM operations

### ISSUE THREAD

**Issue by srikanthmalla** [arc-research-lab/CHARM#6]
Hi,

In the paper, there are evaluations on non-GEMM operations such as softmax, layernorm, etc. However, I think the current release does not include them. I am wondering if you have an implementation or any references.

**Comment by peipeizhou-eecs** [comment]
@srikanthmalla Thank you for your interests! Regarding the Non-GEMM code, we have some manuscripts that are still being reviewed. We will let you know when this part is released. The easiest way is to star and watch this repo for the next release.

**Comment by logosAllen** [comment]
Hi,
I am also curious about the non-GEMM part too, hope to see it.
Thank you.

**Comment by peipeizhou-eecs** [comment]
> Hi, I am also curious about the non-GEMM part too, hope to see it. Thank you.

Sure, thank you for your interest!
